name: docker-build-push
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Extract the version
      id: version
      run: |
        SHA=$GITHUB_SHA
        echo tag is : $SHA
    - name: docker build and publish
      run: |
        docker version
        docker login --username ${{ secrets.DOKCKER_USER_NAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker build --build-arg BUILD_VERSION=$PUSH_TAG_VERSION -t gkarthics/gh-actions-test:$PUSH_TAG_VERSION .
        docker push gkarthics/gh-actions-test
