name: docker-build-push
on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prints the version of the commit
      run: echo $GITHUB_SHA
    - name: docker build and publish
      run: |
        docker version
        docker login --username ${{ secrets.DOKCKER_USER_NAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker build --build-arg BUILD_VERSION=$GITHUB_REF -t gkarthics/gh-actions-test:$GITHUB_REF .
        docker push gkarthics/gh-actions-test
