name: docker-build-push
on:
  release:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prints the version of the commit
      run: |
        echo $GITHUB_REF
        echo $PUSH_TAG_VERSION
        echo $GITHUB_REF | grep -o "[a-z][0-9][\.][0-9]$"
    - name: docker build and publish
      run: |
        docker version
        docker login --username ${{ secrets.DOKCKER_USER_NAME }} --password ${{ secrets.DOCKER_PASSWORD }}
        docker build --build-arg BUILD_VERSION=$PUSH_TAG_VERSION -t gkarthics/gh-actions-test:$PUSH_TAG_VERSION .
        docker push gkarthics/gh-actions-test
