name: docker-build-push
on:
  push:
    branches: [ master ]

jobs:
  build:
    container: gkarthics/swagger-validate:0.0.1 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: validate
      run: validate .
