name: docker-build-push
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: gkarthics/swagger-validate:0.0.1 
    - name: validate
      run: validate .
