name: docker-build-push
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker build and publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: gkarthics/gh-actions-test
        username: ${{ secrets.DOKCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
